---
abstract: 'Images of network devices with clickable HTML imagemaps'
author:
  - 'Oliver Gorwits C<< <oliver.gorwits@oucs.ox.ac.uk> >>'
build_requires:
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Net::Appliance::Frontpanel
name: Net-Appliance-Frontpanel
no_index:
  directory:
    - share
    - share
    - inc
    - t
    - examples
requires:
  Carp: 0
  Config::Any: 0
  Config::Tiny: 0
  DBI: 0
  File::Basename: 0
  File::ShareDir: 0
  File::Temp: 0
  Getopt::Long: 0
  HTML::Entities: 0
  Imager: 0
  List::Util: 0
  Moose: 0
  MooseX::LogDispatch: 0
  MooseX::Object::Pluggable: 0
  URI::Escape: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
